[package]
name = "rust"
version = "0.1.0"
edition = "2024"
description = "Godot GDExtension for Some 2D Game"
license = "MIT"
repository = "https://github.com/int34n0s/kik-pok-game"
keywords = ["godot", "game", "multiplayer"]
categories = ["games"]

[lib]
crate-type = ["cdylib"]

[features]
remote-db = []

[dependencies]
godot = "0.4.5"

spacetimedb-sdk = { workspace = true }

thiserror = "2.0.12"
