[package]
name = "rust"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[features]
remote-db = []

[dependencies]
godot = "0.4.0"

spacetimedb-sdk = { workspace = true }

thiserror = "2.0.12"
lazy_static = "1.5.0"
chrono = "0.4.41"
