// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::db_vector_2_type::DbVector2;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Coin {
    pub coin_id: u64,
    pub position: DbVector2,
    pub scene_id: u32,
    pub collected_by: Option<__sdk::Identity>,
}

impl __sdk::InModule for Coin {
    type Module = super::RemoteModule;
}
