// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit e107144998a2ca83ae87f905ff8a6eb5a50ff504).

#![allow(unused, clippy::all)]
use super::coin_type::Coin;
use super::db_vector_2_type::DbVector2;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `coin`.
///
/// Obtain a handle from the [`CoinTableAccess::coin`] method on [`super::RemoteTables`],
/// like `ctx.db.coin()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.coin().on_insert(...)`.
pub struct CoinTableHandle<'ctx> {
    imp: __sdk::TableHandle<Coin>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `coin`.
///
/// Implemented for [`super::RemoteTables`].
pub trait CoinTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`CoinTableHandle`], which mediates access to the table `coin`.
    fn coin(&self) -> CoinTableHandle<'_>;
}

impl CoinTableAccess for super::RemoteTables {
    fn coin(&self) -> CoinTableHandle<'_> {
        CoinTableHandle {
            imp: self.imp.get_table::<Coin>("coin"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct CoinInsertCallbackId(__sdk::CallbackId);
pub struct CoinDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for CoinTableHandle<'ctx> {
    type Row = Coin;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Coin> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = CoinInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CoinInsertCallbackId {
        CoinInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CoinInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = CoinDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CoinDeleteCallbackId {
        CoinDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CoinDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Coin>("coin");
    _table.add_unique_constraint::<u64>("coin_id", |row| &row.coin_id);
}
pub struct CoinUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for CoinTableHandle<'ctx> {
    type UpdateCallbackId = CoinUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CoinUpdateCallbackId {
        CoinUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CoinUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Coin>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Coin>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `coin_id` unique index on the table `coin`,
/// which allows point queries on the field of the same name
/// via the [`CoinCoinIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.coin().coin_id().find(...)`.
pub struct CoinCoinIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Coin, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> CoinTableHandle<'ctx> {
    /// Get a handle on the `coin_id` unique index on the table `coin`.
    pub fn coin_id(&self) -> CoinCoinIdUnique<'ctx> {
        CoinCoinIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("coin_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> CoinCoinIdUnique<'ctx> {
    /// Find the subscribed row whose `coin_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Coin> {
        self.imp.find(col_val)
    }
}
