// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::db_vector_2_type::DbVector2;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CollectCoinArgs {
    pub position: DbVector2,
}

impl From<CollectCoinArgs> for super::Reducer {
    fn from(args: CollectCoinArgs) -> Self {
        Self::CollectCoin {
            position: args.position,
        }
    }
}

impl __sdk::InModule for CollectCoinArgs {
    type Module = super::RemoteModule;
}

pub struct CollectCoinCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `collect_coin`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait collect_coin {
    /// Request that the remote module invoke the reducer `collect_coin` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_collect_coin`] callbacks.
    fn collect_coin(&self, position: DbVector2) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `collect_coin`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`CollectCoinCallbackId`] can be passed to [`Self::remove_on_collect_coin`]
    /// to cancel the callback.
    fn on_collect_coin(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &DbVector2) + Send + 'static,
    ) -> CollectCoinCallbackId;
    /// Cancel a callback previously registered by [`Self::on_collect_coin`],
    /// causing it not to run in the future.
    fn remove_on_collect_coin(&self, callback: CollectCoinCallbackId);
}

impl collect_coin for super::RemoteReducers {
    fn collect_coin(&self, position: DbVector2) -> __sdk::Result<()> {
        self.imp
            .call_reducer("collect_coin", CollectCoinArgs { position })
    }
    fn on_collect_coin(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &DbVector2) + Send + 'static,
    ) -> CollectCoinCallbackId {
        CollectCoinCallbackId(self.imp.on_reducer(
            "collect_coin",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::CollectCoin { position },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, position)
            }),
        ))
    }
    fn remove_on_collect_coin(&self, callback: CollectCoinCallbackId) {
        self.imp.remove_on_reducer("collect_coin", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `collect_coin`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_collect_coin {
    /// Set the call-reducer flags for the reducer `collect_coin` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn collect_coin(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_collect_coin for super::SetReducerFlags {
    fn collect_coin(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("collect_coin", flags);
    }
}
