// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::db_vector_2_type::DbVector2;
use super::green_slime_type::GreenSlime;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `green_slime`.
///
/// Obtain a handle from the [`GreenSlimeTableAccess::green_slime`] method on [`super::RemoteTables`],
/// like `ctx.db.green_slime()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.green_slime().on_insert(...)`.
pub struct GreenSlimeTableHandle<'ctx> {
    imp: __sdk::TableHandle<GreenSlime>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `green_slime`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GreenSlimeTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GreenSlimeTableHandle`], which mediates access to the table `green_slime`.
    fn green_slime(&self) -> GreenSlimeTableHandle<'_>;
}

impl GreenSlimeTableAccess for super::RemoteTables {
    fn green_slime(&self) -> GreenSlimeTableHandle<'_> {
        GreenSlimeTableHandle {
            imp: self.imp.get_table::<GreenSlime>("green_slime"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GreenSlimeInsertCallbackId(__sdk::CallbackId);
pub struct GreenSlimeDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for GreenSlimeTableHandle<'ctx> {
    type Row = GreenSlime;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = GreenSlime> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = GreenSlimeInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GreenSlimeInsertCallbackId {
        GreenSlimeInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GreenSlimeInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = GreenSlimeDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GreenSlimeDeleteCallbackId {
        GreenSlimeDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GreenSlimeDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<GreenSlime>("green_slime");
    _table.add_unique_constraint::<u64>("green_slime_id", |row| &row.green_slime_id);
}
pub struct GreenSlimeUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for GreenSlimeTableHandle<'ctx> {
    type UpdateCallbackId = GreenSlimeUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GreenSlimeUpdateCallbackId {
        GreenSlimeUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GreenSlimeUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<GreenSlime>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<GreenSlime>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `green_slime_id` unique index on the table `green_slime`,
/// which allows point queries on the field of the same name
/// via the [`GreenSlimeGreenSlimeIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.green_slime().green_slime_id().find(...)`.
pub struct GreenSlimeGreenSlimeIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<GreenSlime, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> GreenSlimeTableHandle<'ctx> {
    /// Get a handle on the `green_slime_id` unique index on the table `green_slime`.
    pub fn green_slime_id(&self) -> GreenSlimeGreenSlimeIdUnique<'ctx> {
        GreenSlimeGreenSlimeIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("green_slime_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> GreenSlimeGreenSlimeIdUnique<'ctx> {
    /// Find the subscribed row whose `green_slime_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<GreenSlime> {
        self.imp.find(col_val)
    }
}
