// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::db_vector_2_type::DbVector2;
use super::direction_type::Direction;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Positioning {
    pub coordinates: DbVector2,
    pub direction: Direction,
    pub in_on_floor: bool,
}

impl __sdk::InModule for Positioning {
    type Module = super::RemoteModule;
}
