// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::direction_type::Direction;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RegisterPlayerArgs {
    pub name: String,
    pub scene_id: u32,
    pub direction: Direction,
}

impl From<RegisterPlayerArgs> for super::Reducer {
    fn from(args: RegisterPlayerArgs) -> Self {
        Self::RegisterPlayer {
            name: args.name,
            scene_id: args.scene_id,
            direction: args.direction,
        }
    }
}

impl __sdk::InModule for RegisterPlayerArgs {
    type Module = super::RemoteModule;
}

pub struct RegisterPlayerCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `register_player`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait register_player {
    /// Request that the remote module invoke the reducer `register_player` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_register_player`] callbacks.
    fn register_player(
        &self,
        name: String,
        scene_id: u32,
        direction: Direction,
    ) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `register_player`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`RegisterPlayerCallbackId`] can be passed to [`Self::remove_on_register_player`]
    /// to cancel the callback.
    fn on_register_player(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String, &u32, &Direction) + Send + 'static,
    ) -> RegisterPlayerCallbackId;
    /// Cancel a callback previously registered by [`Self::on_register_player`],
    /// causing it not to run in the future.
    fn remove_on_register_player(&self, callback: RegisterPlayerCallbackId);
}

impl register_player for super::RemoteReducers {
    fn register_player(
        &self,
        name: String,
        scene_id: u32,
        direction: Direction,
    ) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "register_player",
            RegisterPlayerArgs {
                name,
                scene_id,
                direction,
            },
        )
    }
    fn on_register_player(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String, &u32, &Direction)
        + Send
        + 'static,
    ) -> RegisterPlayerCallbackId {
        RegisterPlayerCallbackId(self.imp.on_reducer(
            "register_player",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::RegisterPlayer {
                                    name,
                                    scene_id,
                                    direction,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, name, scene_id, direction)
            }),
        ))
    }
    fn remove_on_register_player(&self, callback: RegisterPlayerCallbackId) {
        self.imp.remove_on_reducer("register_player", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `register_player`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_register_player {
    /// Set the call-reducer flags for the reducer `register_player` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn register_player(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_register_player for super::SetReducerFlags {
    fn register_player(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("register_player", flags);
    }
}
