// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::db_vector_2_type::DbVector2;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RegisterCoinArgs {
    pub position: DbVector2,
    pub scene_id: u32,
}

impl From<RegisterCoinArgs> for super::Reducer {
    fn from(args: RegisterCoinArgs) -> Self {
        Self::RegisterCoin {
            position: args.position,
            scene_id: args.scene_id,
        }
    }
}

impl __sdk::InModule for RegisterCoinArgs {
    type Module = super::RemoteModule;
}

pub struct RegisterCoinCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `register_coin`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait register_coin {
    /// Request that the remote module invoke the reducer `register_coin` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_register_coin`] callbacks.
    fn register_coin(&self, position: DbVector2, scene_id: u32) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `register_coin`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`RegisterCoinCallbackId`] can be passed to [`Self::remove_on_register_coin`]
    /// to cancel the callback.
    fn on_register_coin(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &DbVector2, &u32) + Send + 'static,
    ) -> RegisterCoinCallbackId;
    /// Cancel a callback previously registered by [`Self::on_register_coin`],
    /// causing it not to run in the future.
    fn remove_on_register_coin(&self, callback: RegisterCoinCallbackId);
}

impl register_coin for super::RemoteReducers {
    fn register_coin(&self, position: DbVector2, scene_id: u32) -> __sdk::Result<()> {
        self.imp
            .call_reducer("register_coin", RegisterCoinArgs { position, scene_id })
    }
    fn on_register_coin(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &DbVector2, &u32) + Send + 'static,
    ) -> RegisterCoinCallbackId {
        RegisterCoinCallbackId(self.imp.on_reducer(
            "register_coin",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::RegisterCoin { position, scene_id },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, position, scene_id)
            }),
        ))
    }
    fn remove_on_register_coin(&self, callback: RegisterCoinCallbackId) {
        self.imp.remove_on_reducer("register_coin", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `register_coin`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_register_coin {
    /// Set the call-reducer flags for the reducer `register_coin` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn register_coin(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_register_coin for super::SetReducerFlags {
    fn register_coin(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("register_coin", flags);
    }
}
