// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::db_vector_2_type::DbVector2;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RegisterSceneArgs {
    pub scene_name: String,
    pub spawn_point: DbVector2,
}

impl From<RegisterSceneArgs> for super::Reducer {
    fn from(args: RegisterSceneArgs) -> Self {
        Self::RegisterScene {
            scene_name: args.scene_name,
            spawn_point: args.spawn_point,
        }
    }
}

impl __sdk::InModule for RegisterSceneArgs {
    type Module = super::RemoteModule;
}

pub struct RegisterSceneCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `register_scene`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait register_scene {
    /// Request that the remote module invoke the reducer `register_scene` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_register_scene`] callbacks.
    fn register_scene(&self, scene_name: String, spawn_point: DbVector2) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `register_scene`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`RegisterSceneCallbackId`] can be passed to [`Self::remove_on_register_scene`]
    /// to cancel the callback.
    fn on_register_scene(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String, &DbVector2) + Send + 'static,
    ) -> RegisterSceneCallbackId;
    /// Cancel a callback previously registered by [`Self::on_register_scene`],
    /// causing it not to run in the future.
    fn remove_on_register_scene(&self, callback: RegisterSceneCallbackId);
}

impl register_scene for super::RemoteReducers {
    fn register_scene(&self, scene_name: String, spawn_point: DbVector2) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "register_scene",
            RegisterSceneArgs {
                scene_name,
                spawn_point,
            },
        )
    }
    fn on_register_scene(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String, &DbVector2) + Send + 'static,
    ) -> RegisterSceneCallbackId {
        RegisterSceneCallbackId(self.imp.on_reducer(
            "register_scene",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::RegisterScene {
                                    scene_name,
                                    spawn_point,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, scene_name, spawn_point)
            }),
        ))
    }
    fn remove_on_register_scene(&self, callback: RegisterSceneCallbackId) {
        self.imp.remove_on_reducer("register_scene", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `register_scene`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_register_scene {
    /// Set the call-reducer flags for the reducer `register_scene` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn register_scene(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_register_scene for super::SetReducerFlags {
    fn register_scene(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("register_scene", flags);
    }
}
