// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::db_player_state_type::DbPlayerState;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SendPlayerStateArgs {
    pub state: DbPlayerState,
}

impl From<SendPlayerStateArgs> for super::Reducer {
    fn from(args: SendPlayerStateArgs) -> Self {
        Self::SendPlayerState { state: args.state }
    }
}

impl __sdk::InModule for SendPlayerStateArgs {
    type Module = super::RemoteModule;
}

pub struct SendPlayerStateCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `send_player_state`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait send_player_state {
    /// Request that the remote module invoke the reducer `send_player_state` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_send_player_state`] callbacks.
    fn send_player_state(&self, state: DbPlayerState) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `send_player_state`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`SendPlayerStateCallbackId`] can be passed to [`Self::remove_on_send_player_state`]
    /// to cancel the callback.
    fn on_send_player_state(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &DbPlayerState) + Send + 'static,
    ) -> SendPlayerStateCallbackId;
    /// Cancel a callback previously registered by [`Self::on_send_player_state`],
    /// causing it not to run in the future.
    fn remove_on_send_player_state(&self, callback: SendPlayerStateCallbackId);
}

impl send_player_state for super::RemoteReducers {
    fn send_player_state(&self, state: DbPlayerState) -> __sdk::Result<()> {
        self.imp
            .call_reducer("send_player_state", SendPlayerStateArgs { state })
    }
    fn on_send_player_state(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &DbPlayerState) + Send + 'static,
    ) -> SendPlayerStateCallbackId {
        SendPlayerStateCallbackId(self.imp.on_reducer(
            "send_player_state",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::SendPlayerState { state },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, state)
            }),
        ))
    }
    fn remove_on_send_player_state(&self, callback: SendPlayerStateCallbackId) {
        self.imp.remove_on_reducer("send_player_state", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `send_player_state`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_send_player_state {
    /// Set the call-reducer flags for the reducer `send_player_state` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn send_player_state(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_send_player_state for super::SetReducerFlags {
    fn send_player_state(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("send_player_state", flags);
    }
}
