// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit e107144998a2ca83ae87f905ff8a6eb5a50ff504).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateTimestampArgs {}

impl From<UpdateTimestampArgs> for super::Reducer {
    fn from(args: UpdateTimestampArgs) -> Self {
        Self::UpdateTimestamp
    }
}

impl __sdk::InModule for UpdateTimestampArgs {
    type Module = super::RemoteModule;
}

pub struct UpdateTimestampCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_timestamp`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_timestamp {
    /// Request that the remote module invoke the reducer `update_timestamp` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_update_timestamp`] callbacks.
    fn update_timestamp(&self) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `update_timestamp`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`UpdateTimestampCallbackId`] can be passed to [`Self::remove_on_update_timestamp`]
    /// to cancel the callback.
    fn on_update_timestamp(
        &self,
        callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> UpdateTimestampCallbackId;
    /// Cancel a callback previously registered by [`Self::on_update_timestamp`],
    /// causing it not to run in the future.
    fn remove_on_update_timestamp(&self, callback: UpdateTimestampCallbackId);
}

impl update_timestamp for super::RemoteReducers {
    fn update_timestamp(&self) -> __sdk::Result<()> {
        self.imp
            .call_reducer("update_timestamp", UpdateTimestampArgs {})
    }
    fn on_update_timestamp(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> UpdateTimestampCallbackId {
        UpdateTimestampCallbackId(self.imp.on_reducer(
            "update_timestamp",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::UpdateTimestamp {},
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx)
            }),
        ))
    }
    fn remove_on_update_timestamp(&self, callback: UpdateTimestampCallbackId) {
        self.imp.remove_on_reducer("update_timestamp", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `update_timestamp`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_update_timestamp {
    /// Set the call-reducer flags for the reducer `update_timestamp` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn update_timestamp(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_update_timestamp for super::SetReducerFlags {
    fn update_timestamp(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("update_timestamp", flags);
    }
}
