[package]
name = "spacetime-module"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
log = "0.4"

itertools = "0.14.0"

spacetimedb = { workspace = true }
