[package]
name = "spacetime-module"
version = "0.1.0"
edition = "2024"
description = "SpacetimeDB server module for Some 2D Game"
license = "MIT"
repository = "https://github.com/int34n0s/kik-pok-game"
keywords = ["spacetimedb", "game", "multiplayer"]
categories = ["games"]

[lib]
crate-type = ["cdylib"]

[dependencies]
log = "0.4"

itertools = "0.14.0"

spacetimedb = { workspace = true }
